# -*- coding: utf-8 -*-
"""BCA Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AISuYF61J8Xj9x8gOQuLQdYVp0-Mi4dw
"""

print("Hello Rutvik!")

# version of python
import sys
print("Python Version: ")
print(sys.version)

import platform

import sys
import keyword
from datetime import datetime

print("Python Version :",platform.python_version())

print("Python Build : ",platform.python_build())

print("Python Compiler: ",platform.python_compiler())

print("Python Implementation: ",platform.python_implementation())

print("Operating System: ",platform.system())
print("OS Version: ",platform.version())

print("Machine: ",platform.machine())
print("Processor: ",platform.processor())

print("Python Executable Path: ",sys.executable)
print("Python Module Path: ",sys.path)
print("Python Version: ",sys.version)


print("Python Keywords List",keyword.kwlist)

print("Current Date and Time: ",datetime.now())