# -*- coding: utf-8 -*-
"""BCA Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AISuYF61J8Xj9x8gOQuLQdYVp0-Mi4dw
"""

print("Hello Rutvik!")

# version of python
import sys
print("Python Version: ")
print(sys.version)

import platform

import sys
import keyword
from datetime import datetime

print("Python Version :",platform.python_version())

print("Python Build : ",platform.python_build())

print("Python Compiler: ",platform.python_compiler())

print("Python Implementation: ",platform.python_implementation())

print("Operating System: ",platform.system())
print("OS Version: ",platform.version())

print("Machine: ",platform.machine())
print("Processor: ",platform.processor())

print("Python Executable Path: ",sys.executable)
print("Python Module Path: ",sys.path)
print("Python Version: ",sys.version)


print("Python Keywords List",keyword.kwlist)

print("Current Date and Time: ",datetime.now())

a = 10
name = "Rutvik Babariya"

print(10)
print(name)

a = b = c = d = e = f = g = 200

x = y = z = 20, 20.5 , "Rutvik "

# type Casting

# int casting
s = "10"
n = int(s)

# float
cnt = 10
n1 = float(cnt)

age = 26
s2 = str(age)

print(n)
print(n1)
print(s2)

# data types
n= 92
f = 3.14
s = "Rutvik"
li = [1,2,3]
d ={'key','value'}
bool = True

print(type(n))
print(type(f))
print(type(s))
print(type(li))
print(type(bool))

# delete the variable

x1= 20

print(x)

del x
print(x)

# to store and display employee information using variables

employee_name = "Rutvik Babariya"
employee_id = "EMP001"
employee_department = "IT (App Developer)"
employee_salary = 150000.00

print("Employee Information:")
print("-------------------------------------------")
print(f"Name: {employee_name}")
print(f"ID: {employee_id}")
print(f"Department: {employee_department}")
print(f"Salary: ₹{employee_salary:.2f}")

# to Store and Print the Details of book using variable

book_title = "The Psychology of Money"
book_author = "Morgan Housel"
publication_year = 2020

print("Book Details:")
print("-------------------------------------------")
print(f"Title: {book_title}")
print(f"Author: {book_author}")
print(f"Publication Year: {publication_year}")

import keyword

print("Keywords:")
print(keyword.kwlist)
print(f"Total Keywords: {len(keyword.kwlist)}")

# Indetations

age = 25

if age >= 22:
  print("Buy BMW")

else :
  print("Not Eligible")

# swapping the number

a = 25
b = 50

print("Before Swapping the Number: ",a)
print("Before Swapping the Number: ",b)

a = a+b
b = a-b
a = a-b

print("After Swapping the Number: ",a)
print("After Swapping the Number: ",b)

# Counting the character in a String

name = "Rutvik Babariya"
character_count = len(name)
print(f"The name '{name}' has {character_count} characters.")

# input and output function
name = input("Enter your name: ")
print("Hello,", name)

# odd even number

number = int(input("Enter a number: "))

if( number %2 == 0) :
       print("Even")
else:
      print("Odd")

user_input = input("Enter two values separated by a space:")
values = user_input.split()

if len(values) == 2:
    a, b = values[0], values[1]
    print("a: ", a)
    print("b: ", b)
else:
    print("Error: Please enter exactly two values separated by a space.")

name = input("Enter your name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
course = input("Enter your course: ")

print("\n--- Your Information ---")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"Course: {course}")

length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))

area = length * width

print(f"The area of the rectangle with length {length} and width {width} is: {area}")

'''
 Create a reciept Layout

 To Understand and implement the use of escape Sequence or character like \t
 in the print Function  for creating a neatly formatted reciept layout in Python.
'''

print("\n--- RECEIPT ---")
print("Item\t\tPrice\tQty\tTotal")
print("---------------------------------")
print("Apple\t\t₹1.00\t2\t₹2.00")
print("Banana\t\t₹0.50\t3\t₹1.50")
print("Orange\t\t₹0.75\t1\t₹0.75")
print("---------------------------------")
print("Subtotal:\t\t\t₹4.25")
print("Tax (8%):\t\t\t₹0.34")
print("Total:\t\t\t₹4.59")
print("\nThank You For Your Purchase!")